---
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/neoera/spring-cloudconfig-foreign-exchange
          username: nazmi.yasin.erdogan@gmail.com
          password: 200638Gthb